"""add_asset_models_phase2

Revision ID: 886f5cfac031
Revises: 39df4e1489ca
Create Date: 2026-01-26 15:40:23.185942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '886f5cfac031'
down_revision = '39df4e1489ca'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='분류 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='분류명'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='설명'),
    sa.Column('level', sa.Integer(), nullable=False, comment='분류 레벨 (1: 대분류, 2: 중분류, 3: 소분류)'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 분류 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['asset_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_categories_code'), 'asset_categories', ['code'], unique=True)
    op.create_index(op.f('ix_asset_categories_id'), 'asset_categories', ['id'], unique=False)
    op.create_table('asset_types',
    sa.Column('code', sa.String(length=20), nullable=False, comment='자산 유형 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='자산 유형명'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='설명'),
    sa.Column('icon', sa.String(length=50), nullable=True, comment='아이콘 이름'),
    sa.Column('is_custom', sa.Boolean(), nullable=False, comment='커스텀 유형 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_types_code'), 'asset_types', ['code'], unique=True)
    op.create_index(op.f('ix_asset_types_id'), 'asset_types', ['id'], unique=False)
    op.create_table('assets',
    sa.Column('asset_code', sa.String(length=50), nullable=False, comment='자산코드 (자동 채번)'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='자산명'),
    sa.Column('description', sa.Text(), nullable=True, comment='자산 설명'),
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='자산 유형 ID'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='자산 분류 ID'),
    sa.Column('location', sa.String(length=200), nullable=True, comment='물리적 위치'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='담당 부서 ID'),
    sa.Column('owner_id', sa.Integer(), nullable=True, comment='자산 소유자 ID'),
    sa.Column('ip_address', sa.String(length=50), nullable=True, comment='IP 주소'),
    sa.Column('mac_address', sa.String(length=50), nullable=True, comment='MAC 주소'),
    sa.Column('hostname', sa.String(length=100), nullable=True, comment='호스트명'),
    sa.Column('os_version', sa.String(length=100), nullable=True, comment='OS 버전'),
    sa.Column('serial_number', sa.String(length=100), nullable=True, comment='시리얼 번호'),
    sa.Column('manufacturer', sa.String(length=100), nullable=True, comment='제조사'),
    sa.Column('model', sa.String(length=100), nullable=True, comment='모델명'),
    sa.Column('specifications', sa.Text(), nullable=True, comment='사양 (JSON)'),
    sa.Column('acquisition_date', sa.Date(), nullable=True, comment='취득일'),
    sa.Column('acquisition_cost', sa.Integer(), nullable=True, comment='취득 비용'),
    sa.Column('warranty_end_date', sa.Date(), nullable=True, comment='보증 만료일'),
    sa.Column('disposal_date', sa.Date(), nullable=True, comment='폐기일'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (도입/운영/변경/폐기)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['asset_categories.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assets_asset_code'), 'assets', ['asset_code'], unique=True)
    op.create_index(op.f('ix_assets_id'), 'assets', ['id'], unique=False)
    op.create_table('asset_assignments',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='담당자 ID'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='역할 (owner/manager/user)'),
    sa.Column('assigned_at', sa.DateTime(), nullable=False, comment='할당 일시'),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='할당자 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_assignments_asset_id'), 'asset_assignments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_assignments_id'), 'asset_assignments', ['id'], unique=False)
    op.create_index(op.f('ix_asset_assignments_user_id'), 'asset_assignments', ['user_id'], unique=False)
    op.create_table('asset_disposals',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('disposal_date', sa.Date(), nullable=False, comment='폐기일'),
    sa.Column('disposal_reason', sa.Text(), nullable=True, comment='폐기 사유'),
    sa.Column('disposal_method', sa.String(length=100), nullable=True, comment='폐기 방법'),
    sa.Column('data_deletion_confirmed', sa.Boolean(), nullable=False, comment='데이터 삭제 확인'),
    sa.Column('data_deletion_method', sa.String(length=200), nullable=True, comment='데이터 삭제 방법'),
    sa.Column('data_deletion_evidence_id', sa.Integer(), nullable=True, comment='데이터 삭제 증적 ID'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='승인자 ID'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='승인 일시'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['data_deletion_evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_disposals_asset_id'), 'asset_disposals', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_disposals_id'), 'asset_disposals', ['id'], unique=False)
    op.create_table('asset_handovers',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('from_user_id', sa.Integer(), nullable=False, comment='인계자 ID'),
    sa.Column('to_user_id', sa.Integer(), nullable=False, comment='인수자 ID'),
    sa.Column('handover_date', sa.Date(), nullable=False, comment='인수인계일'),
    sa.Column('checklist_items', sa.Text(), nullable=True, comment='체크리스트 항목 (JSON)'),
    sa.Column('checklist_completed', sa.Boolean(), nullable=False, comment='체크리스트 완료 여부'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='승인자 ID'),
    sa.Column('approved_at', sa.DateTime(), nullable=True, comment='승인 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['from_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['to_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_handovers_asset_id'), 'asset_handovers', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_handovers_id'), 'asset_handovers', ['id'], unique=False)
    op.create_table('asset_histories',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='변경 유형 (create/update/delete/valuation/assignment)'),
    sa.Column('field_name', sa.String(length=100), nullable=True, comment='변경 필드명'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='이전 값'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='새 값'),
    sa.Column('changed_by', sa.Integer(), nullable=True, comment='변경자 ID'),
    sa.Column('changed_at', sa.DateTime(), nullable=False, comment='변경 일시'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_histories_asset_id'), 'asset_histories', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_histories_id'), 'asset_histories', ['id'], unique=False)
    op.create_table('asset_valuations',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('confidentiality', sa.Integer(), nullable=False, comment='기밀성 (1: 하, 2: 중, 3: 상)'),
    sa.Column('integrity', sa.Integer(), nullable=False, comment='무결성 (1: 하, 2: 중, 3: 상)'),
    sa.Column('availability', sa.Integer(), nullable=False, comment='가용성 (1: 하, 2: 중, 3: 상)'),
    sa.Column('importance_level', sa.Integer(), nullable=True, comment='자산 중요도 (자동 계산)'),
    sa.Column('evaluation_reason', sa.Text(), nullable=True, comment='평가 사유'),
    sa.Column('evaluated_by', sa.Integer(), nullable=True, comment='평가자 ID'),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True, comment='평가 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_valuations_asset_id'), 'asset_valuations', ['asset_id'], unique=False)
    op.create_index(op.f('ix_asset_valuations_id'), 'asset_valuations', ['id'], unique=False)
    op.create_index(op.f('ix_notification_settings_notification_type'), 'notification_settings', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_settings_user_id'), 'notification_settings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_settings_user_id'), table_name='notification_settings')
    op.drop_index(op.f('ix_notification_settings_notification_type'), table_name='notification_settings')
    op.drop_index(op.f('ix_asset_valuations_id'), table_name='asset_valuations')
    op.drop_index(op.f('ix_asset_valuations_asset_id'), table_name='asset_valuations')
    op.drop_table('asset_valuations')
    op.drop_index(op.f('ix_asset_histories_id'), table_name='asset_histories')
    op.drop_index(op.f('ix_asset_histories_asset_id'), table_name='asset_histories')
    op.drop_table('asset_histories')
    op.drop_index(op.f('ix_asset_handovers_id'), table_name='asset_handovers')
    op.drop_index(op.f('ix_asset_handovers_asset_id'), table_name='asset_handovers')
    op.drop_table('asset_handovers')
    op.drop_index(op.f('ix_asset_disposals_id'), table_name='asset_disposals')
    op.drop_index(op.f('ix_asset_disposals_asset_id'), table_name='asset_disposals')
    op.drop_table('asset_disposals')
    op.drop_index(op.f('ix_asset_assignments_user_id'), table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_id'), table_name='asset_assignments')
    op.drop_index(op.f('ix_asset_assignments_asset_id'), table_name='asset_assignments')
    op.drop_table('asset_assignments')
    op.drop_index(op.f('ix_assets_id'), table_name='assets')
    op.drop_index(op.f('ix_assets_asset_code'), table_name='assets')
    op.drop_table('assets')
    op.drop_index(op.f('ix_asset_types_id'), table_name='asset_types')
    op.drop_index(op.f('ix_asset_types_code'), table_name='asset_types')
    op.drop_table('asset_types')
    op.drop_index(op.f('ix_asset_categories_id'), table_name='asset_categories')
    op.drop_index(op.f('ix_asset_categories_code'), table_name='asset_categories')
    op.drop_table('asset_categories')
    # ### end Alembic commands ###
