"""initial_schema

Revision ID: 39df4e1489ca
Revises: 
Create Date: 2026-01-22 06:03:44.560651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39df4e1489ca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_domains',
    sa.Column('code', sa.String(length=10), nullable=False, comment='영역 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='영역명'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_domains_code'), 'control_domains', ['code'], unique=True)
    op.create_index(op.f('ix_control_domains_id'), 'control_domains', ['id'], unique=False)
    op.create_table('departments',
    sa.Column('name', sa.String(length=100), nullable=False, comment='부서명'),
    sa.Column('code', sa.String(length=50), nullable=False, comment='부서 코드'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 부서 ID'),
    sa.Column('manager_id', sa.Integer(), nullable=True, comment='부서장 ID (순환 참조 방지를 위해 FK 제거)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='부서 설명'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_code'), 'departments', ['code'], unique=True)
    op.create_index(op.f('ix_departments_id'), 'departments', ['id'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=50), nullable=False, comment='역할명'),
    sa.Column('description', sa.String(length=255), nullable=True, comment='역할 설명'),
    sa.Column('permissions', sa.Text(), nullable=False, comment='권한 JSON (쉼표로 구분)'),
    sa.Column('is_system_role', sa.Boolean(), nullable=False, comment='시스템 기본 역할 여부'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_id'), 'roles', ['id'], unique=False)
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('control_categories',
    sa.Column('domain_id', sa.Integer(), nullable=False, comment='영역 ID'),
    sa.Column('code', sa.String(length=10), nullable=False, comment='카테고리 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='카테고리명'),
    sa.Column('description', sa.Text(), nullable=True, comment='설명'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['domain_id'], ['control_domains.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_categories_code'), 'control_categories', ['code'], unique=True)
    op.create_index(op.f('ix_control_categories_id'), 'control_categories', ['id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='이메일'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='암호화된 비밀번호'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='이름'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='전화번호'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='부서 ID'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='슈퍼유저 여부'),
    sa.Column('is_mfa_enabled', sa.Boolean(), nullable=False, comment='2FA 활성화'),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True, comment='TOTP 시크릿'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='로그인 실패 횟수'),
    sa.Column('locked_until', sa.DateTime(), nullable=True, comment='계정 잠금 해제 시간'),
    sa.Column('password_changed_at', sa.DateTime(), nullable=False, comment='비밀번호 변경 시간'),
    sa.Column('last_login_at', sa.DateTime(), nullable=True, comment='마지막 로그인 시간'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='마지막 로그인 IP'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('user_id', sa.Integer(), nullable=True, comment='사용자 ID'),
    sa.Column('user_email', sa.String(length=255), nullable=True, comment='사용자 이메일 (스냅샷)'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='사용자 이름 (스냅샷)'),
    sa.Column('action', sa.String(length=50), nullable=False, comment='액션 (create/read/update/delete/login/logout 등)'),
    sa.Column('resource_type', sa.String(length=50), nullable=False, comment='리소스 타입 (user/evidence/audit 등)'),
    sa.Column('resource_id', sa.Integer(), nullable=True, comment='리소스 ID'),
    sa.Column('old_value', sa.Text(), nullable=True, comment='변경 전 값 JSON'),
    sa.Column('new_value', sa.Text(), nullable=True, comment='변경 후 값 JSON'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='IP 주소'),
    sa.Column('user_agent', sa.String(length=500), nullable=True, comment='User Agent'),
    sa.Column('request_method', sa.String(length=10), nullable=True, comment='HTTP 메서드'),
    sa.Column('request_path', sa.String(length=500), nullable=True, comment='요청 경로'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP 상태 코드'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='오류 메시지'),
    sa.Column('previous_hash', sa.String(length=64), nullable=True, comment='이전 로그 해시'),
    sa.Column('current_hash', sa.String(length=64), nullable=False, comment='현재 로그 해시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_current_hash'), 'audit_logs', ['current_hash'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('audit_plans',
    sa.Column('title', sa.String(length=255), nullable=False, comment='감사 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='감사 설명'),
    sa.Column('audit_type', sa.String(length=50), nullable=False, comment='감사 유형 (internal/external/certification)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='감사 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='감사 종료일'),
    sa.Column('scope', sa.Text(), nullable=False, comment='감사 범위 (부서, 프로세스 등)'),
    sa.Column('control_domains', sa.Text(), nullable=True, comment='대상 통제영역 JSON (쉼표로 구분)'),
    sa.Column('lead_auditor_id', sa.Integer(), nullable=False, comment='수감사인 ID'),
    sa.Column('team_members', sa.Text(), nullable=True, comment='감사팀 구성원 ID JSON'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (planning/in_progress/completed/cancelled)'),
    sa.Column('overall_result', sa.String(length=20), nullable=True, comment='전체 결과 (conformity/non_conformity)'),
    sa.Column('final_report_path', sa.String(length=500), nullable=True, comment='최종 보고서 파일 경로'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lead_auditor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_plans_id'), 'audit_plans', ['id'], unique=False)
    op.create_table('control_items',
    sa.Column('category_id', sa.Integer(), nullable=False, comment='카테고리 ID'),
    sa.Column('code', sa.String(length=20), nullable=False, comment='통제항목 번호'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='통제항목 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='통제항목 설명'),
    sa.Column('objective', sa.Text(), nullable=True, comment='통제 목적'),
    sa.Column('requirements', sa.Text(), nullable=True, comment='요구사항'),
    sa.Column('is_required', sa.Boolean(), nullable=False, comment='필수 통제항목 여부'),
    sa.Column('is_personal_info', sa.Boolean(), nullable=False, comment='개인정보보호 통제항목 여부'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('tags', sa.String(length=255), nullable=True, comment='태그 (쉼표로 구분)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['control_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_items_code'), 'control_items', ['code'], unique=True)
    op.create_index(op.f('ix_control_items_id'), 'control_items', ['id'], unique=False)
    op.create_table('evidence_templates',
    sa.Column('name', sa.String(length=255), nullable=False, comment='템플릿명'),
    sa.Column('description', sa.Text(), nullable=True, comment='템플릿 설명'),
    sa.Column('category', sa.String(length=50), nullable=False, comment='템플릿 카테고리 (점검표/서약서/회의록 등)'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='템플릿 파일 경로'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='템플릿 파일명'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME 타입'),
    sa.Column('is_system_template', sa.Boolean(), nullable=False, comment='시스템 기본 템플릿 여부'),
    sa.Column('created_by', sa.Integer(), nullable=True, comment='생성자 ID'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='다운로드 횟수'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_templates_id'), 'evidence_templates', ['id'], unique=False)
    op.create_table('evidences',
    sa.Column('title', sa.String(length=255), nullable=False, comment='증적 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='증적 설명'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='MinIO 파일 경로'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='원본 파일명'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='파일 크기 (bytes)'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='SHA256 파일 해시'),
    sa.Column('mime_type', sa.String(length=100), nullable=True, comment='MIME 타입'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='버전'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (active/expired/archived)'),
    sa.Column('valid_from', sa.Date(), nullable=True, comment='유효 시작일'),
    sa.Column('valid_until', sa.Date(), nullable=True, comment='유효 만료일'),
    sa.Column('uploader_id', sa.Integer(), nullable=False, comment='업로드한 사용자 ID'),
    sa.Column('author', sa.String(length=100), nullable=True, comment='증적 작성자'),
    sa.Column('reviewed_by', sa.Integer(), nullable=True, comment='검토자 ID'),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True, comment='검토 일시'),
    sa.Column('review_comment', sa.Text(), nullable=True, comment='검토 의견'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['uploader_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_id'), 'evidences', ['id'], unique=False)
    op.create_table('notification_settings',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='알림 유형'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False, comment='이메일 알림 활성화'),
    sa.Column('app_enabled', sa.Boolean(), nullable=False, comment='앱 알림 활성화'),
    sa.Column('frequency', sa.String(length=20), nullable=False, comment='알림 주기 (realtime/daily/weekly)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_notification_settings_id'), 'notification_settings', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='수신자 ID'),
    sa.Column('notification_type', sa.String(length=50), nullable=False, comment='알림 유형 (evidence_expiring/task_due/nc_assigned/audit_scheduled 등)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='알림 제목'),
    sa.Column('message', sa.Text(), nullable=False, comment='알림 메시지'),
    sa.Column('priority', sa.String(length=20), nullable=False, comment='우선순위 (low/normal/high/urgent)'),
    sa.Column('link_url', sa.String(length=500), nullable=True, comment='관련 페이지 URL'),
    sa.Column('reference_type', sa.String(length=50), nullable=True, comment='참조 타입 (evidence/task/audit 등)'),
    sa.Column('reference_id', sa.Integer(), nullable=True, comment='참조 ID'),
    sa.Column('is_read', sa.Boolean(), nullable=False, comment='읽음 여부'),
    sa.Column('read_at', sa.DateTime(), nullable=True, comment='읽은 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_is_read'), 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('user_role_assignments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True, comment='할당자'),
    sa.Column('assigned_at', sa.DateTime(), nullable=False, comment='할당 시간'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_role_assignments_id'), 'user_role_assignments', ['id'], unique=False)
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    op.create_table('audit_checklists',
    sa.Column('audit_plan_id', sa.Integer(), nullable=False, comment='감사 계획 ID'),
    sa.Column('control_item_id', sa.Integer(), nullable=False, comment='통제항목 ID'),
    sa.Column('question', sa.Text(), nullable=False, comment='점검 질문'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checklists_id'), 'audit_checklists', ['id'], unique=False)
    op.create_table('auditor_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False, comment='사용자 ID'),
    sa.Column('audit_plan_id', sa.Integer(), nullable=False, comment='감사 계획 ID'),
    sa.Column('valid_from', sa.DateTime(), nullable=False, comment='유효 시작일'),
    sa.Column('valid_until', sa.DateTime(), nullable=False, comment='유효 만료일'),
    sa.Column('access_scope', sa.Text(), nullable=True, comment='접근 범위 JSON'),
    sa.Column('allow_download', sa.Boolean(), nullable=False, comment='다운로드 허용 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auditor_accounts_id'), 'auditor_accounts', ['id'], unique=False)
    op.create_table('control_item_evidence_mappings',
    sa.Column('control_item_id', sa.Integer(), nullable=False, comment='통제항목 ID'),
    sa.Column('evidence_id', sa.Integer(), nullable=False, comment='증적 ID'),
    sa.Column('mapped_by', sa.Integer(), nullable=True, comment='매핑한 사용자 ID'),
    sa.Column('mapping_note', sa.Text(), nullable=True, comment='매핑 메모'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['mapped_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_item_evidence_mappings_id'), 'control_item_evidence_mappings', ['id'], unique=False)
    op.create_table('control_item_evidences',
    sa.Column('control_item_id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.PrimaryKeyConstraint('control_item_id', 'evidence_id')
    )
    op.create_table('evidence_versions',
    sa.Column('evidence_id', sa.Integer(), nullable=False, comment='증적 ID'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='버전'),
    sa.Column('file_path', sa.String(length=500), nullable=False, comment='파일 경로'),
    sa.Column('file_name', sa.String(length=255), nullable=False, comment='파일명'),
    sa.Column('file_size', sa.Integer(), nullable=False, comment='파일 크기'),
    sa.Column('file_hash', sa.String(length=64), nullable=False, comment='파일 해시'),
    sa.Column('uploaded_by', sa.Integer(), nullable=False, comment='업로드한 사용자 ID'),
    sa.Column('change_description', sa.Text(), nullable=True, comment='변경 설명'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_versions_id'), 'evidence_versions', ['id'], unique=False)
    op.create_table('non_conformities',
    sa.Column('audit_plan_id', sa.Integer(), nullable=False, comment='감사 계획 ID'),
    sa.Column('control_item_id', sa.Integer(), nullable=False, comment='통제항목 ID'),
    sa.Column('nc_type', sa.String(length=20), nullable=False, comment='부적합 유형 (major/minor/observation)'),
    sa.Column('severity', sa.String(length=20), nullable=False, comment='심각도 (critical/high/medium/low)'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='부적합 제목'),
    sa.Column('description', sa.Text(), nullable=False, comment='부적합 내용'),
    sa.Column('requirement', sa.Text(), nullable=False, comment='요구사항'),
    sa.Column('evidence', sa.Text(), nullable=True, comment='근거'),
    sa.Column('responsible_person_id', sa.Integer(), nullable=False, comment='조치 담당자 ID'),
    sa.Column('department_id', sa.Integer(), nullable=True, comment='담당 부서 ID'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (open/in_progress/resolved/closed/reopened)'),
    sa.Column('detected_at', sa.Date(), nullable=False, comment='적발일'),
    sa.Column('due_date', sa.Date(), nullable=False, comment='시정 기한'),
    sa.Column('closed_at', sa.Date(), nullable=True, comment='종료일'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audit_plan_id'], ['audit_plans.id'], ),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_non_conformities_id'), 'non_conformities', ['id'], unique=False)
    op.create_table('scheduled_tasks',
    sa.Column('title', sa.String(length=255), nullable=False, comment='활동 제목'),
    sa.Column('description', sa.Text(), nullable=True, comment='활동 설명'),
    sa.Column('task_type', sa.String(length=50), nullable=False, comment='활동 유형 (vulnerability_scan/backup_test/review 등)'),
    sa.Column('frequency', sa.String(length=50), nullable=False, comment='주기 (daily/weekly/monthly/quarterly/yearly)'),
    sa.Column('cron_expression', sa.String(length=100), nullable=True, comment='Cron 표현식 (선택적)'),
    sa.Column('assignee_id', sa.Integer(), nullable=False, comment='담당자 ID'),
    sa.Column('escalation_to_id', sa.Integer(), nullable=True, comment='에스컬레이션 대상 ID'),
    sa.Column('control_item_id', sa.Integer(), nullable=True, comment='관련 통제항목 ID'),
    sa.Column('last_executed_at', sa.DateTime(), nullable=True, comment='마지막 실행 일시'),
    sa.Column('next_execution_at', sa.DateTime(), nullable=False, comment='다음 실행 예정 일시'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (active/paused/completed)'),
    sa.Column('escalation_days', sa.Integer(), nullable=False, comment='에스컬레이션까지 일수'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.ForeignKeyConstraint(['escalation_to_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheduled_tasks_id'), 'scheduled_tasks', ['id'], unique=False)
    op.create_table('audit_checklist_results',
    sa.Column('checklist_id', sa.Integer(), nullable=False, comment='체크리스트 ID'),
    sa.Column('result', sa.String(length=20), nullable=False, comment='점검 결과 (conformity/non_conformity/observation/not_applicable)'),
    sa.Column('finding', sa.Text(), nullable=True, comment='발견사항'),
    sa.Column('evidence_reference', sa.Text(), nullable=True, comment='근거 증적 참조 (증적 ID 목록)'),
    sa.Column('auditor_id', sa.Integer(), nullable=False, comment='점검자 ID'),
    sa.Column('checked_at', sa.DateTime(), nullable=False, comment='점검 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['auditor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['checklist_id'], ['audit_checklists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_checklist_results_id'), 'audit_checklist_results', ['id'], unique=False)
    op.create_table('corrective_actions',
    sa.Column('non_conformity_id', sa.Integer(), nullable=False, comment='부적합 ID'),
    sa.Column('action_plan', sa.Text(), nullable=False, comment='시정조치 계획'),
    sa.Column('root_cause', sa.Text(), nullable=True, comment='근본 원인 분석'),
    sa.Column('preventive_measures', sa.Text(), nullable=True, comment='재발 방지 대책'),
    sa.Column('responsible_person_id', sa.Integer(), nullable=False, comment='담당자 ID'),
    sa.Column('planned_completion_date', sa.Date(), nullable=False, comment='완료 예정일'),
    sa.Column('actual_completion_date', sa.Date(), nullable=True, comment='실제 완료일'),
    sa.Column('result_description', sa.Text(), nullable=True, comment='실행 결과 설명'),
    sa.Column('result_evidence_id', sa.Integer(), nullable=True, comment='결과 증적 ID'),
    sa.Column('verified_by', sa.Integer(), nullable=True, comment='검증자 ID'),
    sa.Column('verified_at', sa.DateTime(), nullable=True, comment='검증 일시'),
    sa.Column('verification_result', sa.String(length=20), nullable=True, comment='검증 결과 (approved/rejected)'),
    sa.Column('verification_comment', sa.Text(), nullable=True, comment='검증 의견'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (planned/in_progress/completed/verified)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['non_conformity_id'], ['non_conformities.id'], ),
    sa.ForeignKeyConstraint(['responsible_person_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['result_evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['verified_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_corrective_actions_id'), 'corrective_actions', ['id'], unique=False)
    op.create_table('task_executions',
    sa.Column('task_id', sa.Integer(), nullable=False, comment='정기 활동 ID'),
    sa.Column('executed_by', sa.Integer(), nullable=False, comment='실행한 사용자 ID'),
    sa.Column('executed_at', sa.DateTime(), nullable=False, comment='실행 일시'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='실행 상태 (completed/failed/skipped)'),
    sa.Column('result_summary', sa.Text(), nullable=True, comment='실행 결과 요약'),
    sa.Column('evidence_id', sa.Integer(), nullable=True, comment='증적 ID (실행 결과)'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], ),
    sa.ForeignKeyConstraint(['executed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scheduled_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_executions_id'), 'task_executions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_task_executions_id'), table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index(op.f('ix_corrective_actions_id'), table_name='corrective_actions')
    op.drop_table('corrective_actions')
    op.drop_index(op.f('ix_audit_checklist_results_id'), table_name='audit_checklist_results')
    op.drop_table('audit_checklist_results')
    op.drop_index(op.f('ix_scheduled_tasks_id'), table_name='scheduled_tasks')
    op.drop_table('scheduled_tasks')
    op.drop_index(op.f('ix_non_conformities_id'), table_name='non_conformities')
    op.drop_table('non_conformities')
    op.drop_index(op.f('ix_evidence_versions_id'), table_name='evidence_versions')
    op.drop_table('evidence_versions')
    op.drop_table('control_item_evidences')
    op.drop_index(op.f('ix_control_item_evidence_mappings_id'), table_name='control_item_evidence_mappings')
    op.drop_table('control_item_evidence_mappings')
    op.drop_index(op.f('ix_auditor_accounts_id'), table_name='auditor_accounts')
    op.drop_table('auditor_accounts')
    op.drop_index(op.f('ix_audit_checklists_id'), table_name='audit_checklists')
    op.drop_table('audit_checklists')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_user_role_assignments_id'), table_name='user_role_assignments')
    op.drop_table('user_role_assignments')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_is_read'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_settings_id'), table_name='notification_settings')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_evidences_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_evidence_templates_id'), table_name='evidence_templates')
    op.drop_table('evidence_templates')
    op.drop_index(op.f('ix_control_items_id'), table_name='control_items')
    op.drop_index(op.f('ix_control_items_code'), table_name='control_items')
    op.drop_table('control_items')
    op.drop_index(op.f('ix_audit_plans_id'), table_name='audit_plans')
    op.drop_table('audit_plans')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_current_hash'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_control_categories_id'), table_name='control_categories')
    op.drop_index(op.f('ix_control_categories_code'), table_name='control_categories')
    op.drop_table('control_categories')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_index(op.f('ix_roles_id'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_departments_id'), table_name='departments')
    op.drop_index(op.f('ix_departments_code'), table_name='departments')
    op.drop_table('departments')
    op.drop_index(op.f('ix_control_domains_id'), table_name='control_domains')
    op.drop_index(op.f('ix_control_domains_code'), table_name='control_domains')
    op.drop_table('control_domains')
    # ### end Alembic commands ###
