"""add_risk_models_phase2

Revision ID: 4c61ee937a05
Revises: 886f5cfac031
Create Date: 2026-01-26 18:34:30.521420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c61ee937a05'
down_revision = '886f5cfac031'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='위협 분류 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='위협 분류명'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='설명'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 분류 ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['threat_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threat_categories_code'), 'threat_categories', ['code'], unique=True)
    op.create_index(op.f('ix_threat_categories_id'), 'threat_categories', ['id'], unique=False)
    op.create_table('vulnerability_categories',
    sa.Column('code', sa.String(length=50), nullable=False, comment='취약점 분류 코드'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='취약점 분류명'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='설명'),
    sa.Column('parent_id', sa.Integer(), nullable=True, comment='상위 분류 ID'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='정렬 순서'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['vulnerability_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_categories_code'), 'vulnerability_categories', ['code'], unique=True)
    op.create_index(op.f('ix_vulnerability_categories_id'), 'vulnerability_categories', ['id'], unique=False)
    op.create_table('threats',
    sa.Column('code', sa.String(length=50), nullable=False, comment='위협 코드'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='위협명'),
    sa.Column('description', sa.Text(), nullable=True, comment='위협 설명'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='위협 분류 ID'),
    sa.Column('threat_level', sa.Integer(), nullable=False, comment='위협 등급 (1: 하, 2: 중, 3: 상)'),
    sa.Column('is_custom', sa.Boolean(), nullable=False, comment='커스텀 위협 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['threat_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_threats_code'), 'threats', ['code'], unique=True)
    op.create_index(op.f('ix_threats_id'), 'threats', ['id'], unique=False)
    op.create_table('vulnerabilities',
    sa.Column('code', sa.String(length=50), nullable=False, comment='취약점 코드'),
    sa.Column('name', sa.String(length=200), nullable=False, comment='취약점명'),
    sa.Column('description', sa.Text(), nullable=True, comment='취약점 설명'),
    sa.Column('category_id', sa.Integer(), nullable=True, comment='취약점 분류 ID'),
    sa.Column('vulnerability_level', sa.Integer(), nullable=False, comment='취약점 등급 (1: 하, 2: 중, 3: 상)'),
    sa.Column('is_custom', sa.Boolean(), nullable=False, comment='커스텀 취약점 여부'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['vulnerability_categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerabilities_code'), 'vulnerabilities', ['code'], unique=True)
    op.create_index(op.f('ix_vulnerabilities_id'), 'vulnerabilities', ['id'], unique=False)
    op.create_table('asset_type_threats',
    sa.Column('asset_type_id', sa.Integer(), nullable=False, comment='자산 유형 ID'),
    sa.Column('threat_id', sa.Integer(), nullable=False, comment='위협 ID'),
    sa.Column('relevance_score', sa.Float(), nullable=False, comment='관련성 점수 (0.0 ~ 1.0)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_type_id'], ['asset_types.id'], ),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asset_type_threats_asset_type_id'), 'asset_type_threats', ['asset_type_id'], unique=False)
    op.create_index(op.f('ix_asset_type_threats_id'), 'asset_type_threats', ['id'], unique=False)
    op.create_index(op.f('ix_asset_type_threats_threat_id'), 'asset_type_threats', ['threat_id'], unique=False)
    op.create_table('doa_configs',
    sa.Column('threshold_value', sa.Integer(), nullable=False, comment='DoA 임계값 (이 값 이상이면 DoA 초과)'),
    sa.Column('effective_date', sa.Date(), nullable=False, comment='적용 시작일'),
    sa.Column('expiry_date', sa.Date(), nullable=True, comment='적용 종료일'),
    sa.Column('approved_by', sa.Integer(), nullable=True, comment='승인자 ID'),
    sa.Column('approval_date', sa.Date(), nullable=True, comment='승인일'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='활성 상태'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doa_configs_id'), 'doa_configs', ['id'], unique=False)
    op.create_table('risk_scenarios',
    sa.Column('name', sa.String(length=200), nullable=False, comment='시나리오명'),
    sa.Column('description', sa.Text(), nullable=True, comment='시나리오 설명'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='평가 시작일'),
    sa.Column('end_date', sa.Date(), nullable=True, comment='평가 종료일'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (draft/in_progress/completed/cancelled)'),
    sa.Column('created_by', sa.Integer(), nullable=False, comment='생성자 ID'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_scenarios_id'), 'risk_scenarios', ['id'], unique=False)
    op.create_table('doa_histories',
    sa.Column('doa_config_id', sa.Integer(), nullable=False, comment='DoA 설정 ID'),
    sa.Column('old_threshold', sa.Integer(), nullable=True, comment='변경 전 임계값'),
    sa.Column('new_threshold', sa.Integer(), nullable=False, comment='변경 후 임계값'),
    sa.Column('change_reason', sa.Text(), nullable=True, comment='변경 사유'),
    sa.Column('changed_by', sa.Integer(), nullable=False, comment='변경자 ID'),
    sa.Column('changed_at', sa.DateTime(), nullable=False, comment='변경 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['doa_config_id'], ['doa_configs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doa_histories_doa_config_id'), 'doa_histories', ['doa_config_id'], unique=False)
    op.create_index(op.f('ix_doa_histories_id'), 'doa_histories', ['id'], unique=False)
    op.create_table('risk_assessments',
    sa.Column('scenario_id', sa.Integer(), nullable=False, comment='시나리오 ID'),
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('threat_id', sa.Integer(), nullable=False, comment='위협 ID'),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False, comment='취약점 ID'),
    sa.Column('asset_value', sa.Integer(), nullable=False, comment='자산 가치 (1: 하, 2: 중, 3: 상)'),
    sa.Column('threat_level', sa.Integer(), nullable=False, comment='위협 등급 (1: 하, 2: 중, 3: 상)'),
    sa.Column('vulnerability_level', sa.Integer(), nullable=False, comment='취약점 등급 (1: 하, 2: 중, 3: 상)'),
    sa.Column('risk_score', sa.Integer(), nullable=True, comment='위험도 점수 (DoR = 자산가치 x 위협 x 취약점)'),
    sa.Column('risk_level', sa.String(length=10), nullable=True, comment='위험 등급 (high/medium/low)'),
    sa.Column('evaluated_by', sa.Integer(), nullable=True, comment='평가자 ID'),
    sa.Column('evaluated_at', sa.DateTime(), nullable=True, comment='평가 일시'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='평가 의견'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['evaluated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scenario_id'], ['risk_scenarios.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['threat_id'], ['threats.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_asset_id'), 'risk_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_id'), 'risk_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_scenario_id'), 'risk_assessments', ['scenario_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_threat_id'), 'risk_assessments', ['threat_id'], unique=False)
    op.create_index(op.f('ix_risk_assessments_vulnerability_id'), 'risk_assessments', ['vulnerability_id'], unique=False)
    op.create_table('soa_records',
    sa.Column('control_item_id', sa.Integer(), nullable=False, comment='통제항목 ID'),
    sa.Column('is_applicable', sa.Boolean(), nullable=False, comment='적용 여부'),
    sa.Column('exclusion_reason', sa.Text(), nullable=True, comment='제외 사유 (미적용 시)'),
    sa.Column('implementation_status', sa.String(length=30), nullable=False, comment='구현 상태 (fully_implemented/partially_implemented/planned/not_implemented/not_applicable)'),
    sa.Column('implementation_evidence', sa.Text(), nullable=True, comment='구현 증적 설명'),
    sa.Column('related_assets', sa.Text(), nullable=True, comment='관련 자산 목록'),
    sa.Column('related_risks', sa.Text(), nullable=True, comment='관련 위험 목록'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['control_item_id'], ['control_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_soa_records_control_item_id'), 'soa_records', ['control_item_id'], unique=True)
    op.create_index(op.f('ix_soa_records_id'), 'soa_records', ['id'], unique=False)
    op.create_table('vulnerability_assessments',
    sa.Column('asset_id', sa.Integer(), nullable=False, comment='자산 ID'),
    sa.Column('vulnerability_id', sa.Integer(), nullable=False, comment='취약점 ID'),
    sa.Column('is_vulnerable', sa.Boolean(), nullable=False, comment='취약 여부'),
    sa.Column('assessment_date', sa.Date(), nullable=False, comment='점검일'),
    sa.Column('assessed_by', sa.Integer(), nullable=True, comment='점검자 ID'),
    sa.Column('findings', sa.Text(), nullable=True, comment='점검 결과/발견 사항'),
    sa.Column('remediation_status', sa.String(length=20), nullable=False, comment='조치 상태 (open/in_progress/closed/accepted)'),
    sa.Column('remediation_date', sa.Date(), nullable=True, comment='조치 완료일'),
    sa.Column('remarks', sa.Text(), nullable=True, comment='비고'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assessed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['vulnerability_id'], ['vulnerabilities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vulnerability_assessments_asset_id'), 'vulnerability_assessments', ['asset_id'], unique=False)
    op.create_index(op.f('ix_vulnerability_assessments_id'), 'vulnerability_assessments', ['id'], unique=False)
    op.create_index(op.f('ix_vulnerability_assessments_vulnerability_id'), 'vulnerability_assessments', ['vulnerability_id'], unique=False)
    op.create_table('risk_treatment_plans',
    sa.Column('risk_assessment_id', sa.Integer(), nullable=False, comment='위험 평가 ID'),
    sa.Column('strategy', sa.String(length=20), nullable=False, comment='처리 전략 (reduce: 감소, avoid: 회피, transfer: 전가, accept: 수용)'),
    sa.Column('description', sa.Text(), nullable=True, comment='처리 계획 설명'),
    sa.Column('assignee_id', sa.Integer(), nullable=True, comment='담당자 ID'),
    sa.Column('due_date', sa.Date(), nullable=True, comment='완료 예정일'),
    sa.Column('budget', sa.Integer(), nullable=True, comment='예산 (원)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='상태 (planned/in_progress/completed/cancelled)'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 일시'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assignee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['risk_assessment_id'], ['risk_assessments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_treatment_plans_id'), 'risk_treatment_plans', ['id'], unique=False)
    op.create_index(op.f('ix_risk_treatment_plans_risk_assessment_id'), 'risk_treatment_plans', ['risk_assessment_id'], unique=False)
    op.create_table('risk_treatment_actions',
    sa.Column('plan_id', sa.Integer(), nullable=False, comment='처리 계획 ID'),
    sa.Column('action_description', sa.Text(), nullable=False, comment='조치 내용'),
    sa.Column('result', sa.Text(), nullable=True, comment='조치 결과'),
    sa.Column('residual_risk_score', sa.Integer(), nullable=True, comment='잔여 위험 점수'),
    sa.Column('completed_by', sa.Integer(), nullable=True, comment='완료자 ID'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='완료 일시'),
    sa.Column('evidence_file_path', sa.String(length=500), nullable=True, comment='증적 파일 경로'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['completed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plan_id'], ['risk_treatment_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_treatment_actions_id'), 'risk_treatment_actions', ['id'], unique=False)
    op.create_index(op.f('ix_risk_treatment_actions_plan_id'), 'risk_treatment_actions', ['plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_risk_treatment_actions_plan_id'), table_name='risk_treatment_actions')
    op.drop_index(op.f('ix_risk_treatment_actions_id'), table_name='risk_treatment_actions')
    op.drop_table('risk_treatment_actions')
    op.drop_index(op.f('ix_risk_treatment_plans_risk_assessment_id'), table_name='risk_treatment_plans')
    op.drop_index(op.f('ix_risk_treatment_plans_id'), table_name='risk_treatment_plans')
    op.drop_table('risk_treatment_plans')
    op.drop_index(op.f('ix_vulnerability_assessments_vulnerability_id'), table_name='vulnerability_assessments')
    op.drop_index(op.f('ix_vulnerability_assessments_id'), table_name='vulnerability_assessments')
    op.drop_index(op.f('ix_vulnerability_assessments_asset_id'), table_name='vulnerability_assessments')
    op.drop_table('vulnerability_assessments')
    op.drop_index(op.f('ix_soa_records_id'), table_name='soa_records')
    op.drop_index(op.f('ix_soa_records_control_item_id'), table_name='soa_records')
    op.drop_table('soa_records')
    op.drop_index(op.f('ix_risk_assessments_vulnerability_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_threat_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_scenario_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_id'), table_name='risk_assessments')
    op.drop_index(op.f('ix_risk_assessments_asset_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_doa_histories_id'), table_name='doa_histories')
    op.drop_index(op.f('ix_doa_histories_doa_config_id'), table_name='doa_histories')
    op.drop_table('doa_histories')
    op.drop_index(op.f('ix_risk_scenarios_id'), table_name='risk_scenarios')
    op.drop_table('risk_scenarios')
    op.drop_index(op.f('ix_doa_configs_id'), table_name='doa_configs')
    op.drop_table('doa_configs')
    op.drop_index(op.f('ix_asset_type_threats_threat_id'), table_name='asset_type_threats')
    op.drop_index(op.f('ix_asset_type_threats_id'), table_name='asset_type_threats')
    op.drop_index(op.f('ix_asset_type_threats_asset_type_id'), table_name='asset_type_threats')
    op.drop_table('asset_type_threats')
    op.drop_index(op.f('ix_vulnerabilities_id'), table_name='vulnerabilities')
    op.drop_index(op.f('ix_vulnerabilities_code'), table_name='vulnerabilities')
    op.drop_table('vulnerabilities')
    op.drop_index(op.f('ix_threats_id'), table_name='threats')
    op.drop_index(op.f('ix_threats_code'), table_name='threats')
    op.drop_table('threats')
    op.drop_index(op.f('ix_vulnerability_categories_id'), table_name='vulnerability_categories')
    op.drop_index(op.f('ix_vulnerability_categories_code'), table_name='vulnerability_categories')
    op.drop_table('vulnerability_categories')
    op.drop_index(op.f('ix_threat_categories_id'), table_name='threat_categories')
    op.drop_index(op.f('ix_threat_categories_code'), table_name='threat_categories')
    op.drop_table('threat_categories')
    # ### end Alembic commands ###
